package:
  name: numdifftools
  version: "0.0.0"

source:
  path: ..


requirements:
  build:
    - python
    - setuptools
    - numpy >=1.9
    - scipy >=0.8

  run:
    - python
    - setuptools
    - numpy >=1.9
    - scipy >=0.8

test:
  imports:
    - numdifftools
    - numdifftools.tests


  requires:
    - pytest
    - pytest-cov
    - line_profiler
    - hypothesis
    - matplotlib
    - algopy >=0.4    [not py36]
    - statsmodels


about:
  home: "https://github.com/pbrod/numdifftools/"
  license: new BSD
  summary: "'Solves automatic numerical differentiation problems in one or more variables.'"
